services:
  chaisebot:
    build:
      context: .
      dockerfile: DOCKERFILE
      network: host
    restart: always
    volumes:
      - /home/lucien/chaisebot:/app
    dns:
      - 1.1.1.1
      - 1.0.0.1